package edu.campus.recycle;
import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api") @CrossOrigin
public class ApiController {
 private final JdbcTemplate db; public ApiController(JdbcTemplate db){this.db=db;}
 @GetMapping("/items") public Map<String,Object> items(@RequestParam(required=false) String keyword,@RequestParam(required=false) Long categoryId,@RequestParam(required=false) String processType,@RequestParam(defaultValue="0") int page,@RequestParam(defaultValue="10") int size){StringBuilder w=new StringBuilder(" WHERE 1=1 "); List<Object> p=new ArrayList<>(); if(keyword!=null&&!keyword.isBlank()){w.append(" AND name LIKE ?");p.add("%"+keyword+"%");} if(categoryId!=null){w.append(" AND category_id=?");p.add(categoryId);} if(processType!=null&&!processType.isBlank()){w.append(" AND process_type=?");p.add(processType);} int offset=page*size; List<Map<String,Object>> rows=db.queryForList("SELECT i.*,c.name category_name,u.real_name owner_name FROM items i JOIN categories c ON c.id=i.category_id JOIN users u ON u.id=i.owner_id"+w+" ORDER BY published_at DESC LIMIT ? OFFSET ?", concat(p,size,offset).toArray()); Map<String,Object> r=new HashMap<>();r.put("records",rows);r.put("total",db.queryForObject("SELECT COUNT(*) FROM items"+w,p.toArray(),Long.class));return r;}
 private List<Object> concat(List<Object> a,Object...x){List<Object> z=new ArrayList<>(a);Collections.addAll(z,x);return z;}
 @GetMapping("/categories") public List<Map<String,Object>> categories(){return db.queryForList("SELECT * FROM categories ORDER BY id");}
 @GetMapping("/stats/overview") public Map<String,Object> stats(){Map<String,Object> r=new HashMap<>();r.put("monthly",db.queryForList("SELECT * FROM v_monthly_item_stats ORDER BY month"));r.put("categories",db.queryForList("SELECT * FROM v_category_stats"));r.put("methods",db.queryForList("SELECT process_type,COUNT(*) quantity FROM items GROUP BY process_type"));r.put("stations",db.queryForList("SELECT * FROM v_station_recycle_stats ORDER BY total_weight DESC"));r.put("ranking",db.queryForList("SELECT u.real_name,SUM(e.change_points) total_points FROM users u JOIN eco_point_records e ON e.user_id=u.id GROUP BY u.id,u.real_name ORDER BY total_points DESC"));return r;}
 @PostMapping("/items") public Map<String,Object> create(@RequestBody Map<String,Object> body){db.update("INSERT INTO items(owner_id,category_id,name,description,condition_level,original_price,current_price,estimated_recycle_price,process_type) VALUES(?,?,?,?,?,?,?,?,?)",body.get("ownerId"),body.get("categoryId"),body.get("name"),body.get("description"),body.getOrDefault("conditionLevel","GOOD"),body.getOrDefault("originalPrice",0),body.getOrDefault("currentPrice",0),body.getOrDefault("estimatedRecyclePrice",0),body.get("processType"));return Map.of("message","发布成功");}
}
