package edu.campus.recycle;
import org.springframework.http.HttpStatus; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.bind.annotation.*; import org.springframework.web.server.ResponseStatusException; import java.util.*;
@RestController @RequestMapping("/api") @CrossOrigin
public class ApiController {
 private final JdbcTemplate db; public ApiController(JdbcTemplate db){this.db=db;} private long id(Object v){return Long.parseLong(String.valueOf(v));}
 private void admin(long uid){Integer n=db.queryForObject("SELECT COUNT(*) FROM users WHERE id=? AND role='ADMIN' AND status='ACTIVE'",Integer.class,uid);if(n==null||n==0)throw new ResponseStatusException(HttpStatus.FORBIDDEN,"需要管理员权限");}
 @PostMapping("/auth/register") public Map<String,Object> register(@RequestBody Map<String,Object>b){db.update("INSERT INTO users(username,password_hash,real_name,phone) VALUES(?,?,?,?)",b.get("username"),b.get("password"),b.get("realName"),b.get("phone"));return Map.of("message","注册成功");}
 @PostMapping("/auth/login") public Map<String,Object> login(@RequestBody Map<String,Object>b){List<Map<String,Object>>r=db.queryForList("SELECT id,username,real_name,phone,role,total_points FROM users WHERE username=? AND password_hash=? AND status='ACTIVE'",b.get("username"),b.get("password"));if(r.isEmpty())throw new ResponseStatusException(HttpStatus.UNAUTHORIZED,"账号或密码错误");return r.get(0);}
 @GetMapping("/users/{id}") public Map<String,Object> user(@PathVariable long id){return db.queryForMap("SELECT id,username,real_name,phone,role,total_points,created_at FROM users WHERE id=?",id);}
 @GetMapping("/items") public Map<String,Object> items(@RequestParam(required=false)String keyword,@RequestParam(required=false)Long categoryId,@RequestParam(required=false)String processType,@RequestParam(required=false)String status,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="10")int size){StringBuilder w=new StringBuilder(" WHERE 1=1 ");List<Object>p=new ArrayList<>();if(keyword!=null&&!keyword.isBlank()){w.append(" AND i.name LIKE ?");p.add("%"+keyword+"%");}if(categoryId!=null){w.append(" AND i.category_id=?");p.add(categoryId);}if(processType!=null&&!processType.isBlank()){w.append(" AND i.process_type=?");p.add(processType);}if(status!=null&&!status.isBlank()){w.append(" AND i.status=?");p.add(status);}int s=Math.min(Math.max(size,1),50);List<Object>q=new ArrayList<>(p);q.add(s);q.add(Math.max(page,0)*s);Map<String,Object>o=new HashMap<>();o.put("records",db.queryForList("SELECT i.*,c.name category_name,u.real_name owner_name FROM items i JOIN categories c ON c.id=i.category_id JOIN users u ON u.id=i.owner_id"+w+" ORDER BY i.published_at DESC LIMIT ? OFFSET ?",q.toArray()));o.put("total",db.queryForObject("SELECT COUNT(*) FROM items i"+w,p.toArray(),Long.class));return o;}
 @GetMapping("/categories")public List<Map<String,Object>> categories(){return db.queryForList("SELECT * FROM categories ORDER BY id");}
 @PostMapping("/items")public Map<String,Object> create(@RequestBody Map<String,Object>b){db.update("INSERT INTO items(owner_id,category_id,name,description,condition_level,original_price,current_price,estimated_recycle_price,process_type) VALUES(?,?,?,?,?,?,?,?,?)",b.get("ownerId"),b.get("categoryId"),b.get("name"),b.get("description"),b.getOrDefault("conditionLevel","GOOD"),b.getOrDefault("originalPrice",0),b.getOrDefault("currentPrice",0),b.getOrDefault("estimatedRecyclePrice",0),b.get("processType"));return Map.of("message","发布成功");}
 @PutMapping("/items/{itemId}")public Map<String,Object> update(@PathVariable long itemId,@RequestBody Map<String,Object>b){long uid=id(b.get("ownerId"));Integer n=db.queryForObject("SELECT COUNT(*) FROM items WHERE id=? AND owner_id=? AND status NOT IN ('COMPLETED','OFFLINE')",Integer.class,itemId,uid);if(n==null||n==0)throw new ResponseStatusException(HttpStatus.FORBIDDEN,"无权修改或物品已完成");db.update("UPDATE items SET name=?,description=?,current_price=?,estimated_recycle_price=?,category_id=? WHERE id=?",b.get("name"),b.get("description"),b.get("currentPrice"),b.get("estimatedRecyclePrice"),b.get("categoryId"),itemId);return Map.of("message","修改成功");}
 @DeleteMapping("/items/{itemId}")public Map<String,Object> offline(@PathVariable long itemId,@RequestParam long ownerId){if(db.update("UPDATE items SET status='OFFLINE' WHERE id=? AND owner_id=? AND status IN ('PENDING','APPLIED')",itemId,ownerId)==0)throw new ResponseStatusException(HttpStatus.CONFLICT,"物品当前不能下架");return Map.of("message","已下架");}
 @PostMapping("/trades")public Map<String,Object> trade(@RequestBody Map<String,Object>b){Map<String,Object>i=db.queryForMap("SELECT owner_id,process_type,current_price,status FROM items WHERE id=?",b.get("itemId"));if(!Set.of("SELL","GIVE").contains(String.valueOf(i.get("process_type")))||!String.valueOf(i.get("status")).equals("PENDING"))throw new ResponseStatusException(HttpStatus.CONFLICT,"物品不可申请");db.update("INSERT INTO trade_orders(item_id,buyer_id,seller_id,process_type,amount) VALUES(?,?,?,?,?)",b.get("itemId"),b.get("buyerId"),i.get("owner_id"),i.get("process_type"),b.getOrDefault("amount",i.get("current_price")));db.update("UPDATE items SET status='APPLIED' WHERE id=?",b.get("itemId"));return Map.of("message","申请已提交");}
 @GetMapping("/trades")public List<Map<String,Object>> trades(@RequestParam long userId,@RequestParam(defaultValue="false")boolean admin){if(admin)admin(userId);String sql="SELECT t.*,i.name item_name,b.real_name buyer_name,s.real_name seller_name FROM trade_orders t JOIN items i ON i.id=t.item_id JOIN users b ON b.id=t.buyer_id JOIN users s ON s.id=t.seller_id"+(admin?"":" WHERE t.buyer_id=? OR t.seller_id=?")+" ORDER BY t.applied_at DESC";return db.queryForList(sql,admin?new Object[]{}:new Object[]{userId,userId});}
 @PutMapping("/trades/{tradeId}/status")public Map<String,Object> tradeStatus(@PathVariable long tradeId,@RequestBody Map<String,Object>b){admin(id(b.get("operatorId")));String next=String.valueOf(b.get("status"));if(!Set.of("PROCESSING","COMPLETED","CANCELLED").contains(next))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"非法状态");Map<String,Object>t=db.queryForMap("SELECT item_id,status FROM trade_orders WHERE id=?",tradeId);String cur=String.valueOf(t.get("status"));if(!(cur.equals("APPLIED")&&(next.equals("PROCESSING")||next.equals("CANCELLED")))&&!(cur.equals("PROCESSING")&&(next.equals("COMPLETED")||next.equals("CANCELLED"))))throw new ResponseStatusException(HttpStatus.CONFLICT,"非法状态转换");db.update("UPDATE trade_orders SET status=?,completed_at=IF(?='COMPLETED',NOW(),completed_at) WHERE id=?",next,next,tradeId);if(next.equals("COMPLETED"))db.update("UPDATE items SET status='COMPLETED',completed_at=NOW() WHERE id=?",t.get("item_id"));return Map.of("message","订单状态已更新");}
 @PostMapping("/recycling-orders")public Map<String,Object> recycle(@RequestBody Map<String,Object>b){db.update("INSERT INTO recycling_orders(item_id,applicant_id,station_id,appointment_at) VALUES(?,?,?,?)",b.get("itemId"),b.get("applicantId"),b.get("stationId"),b.get("appointmentAt"));db.update("UPDATE items SET status='APPLIED' WHERE id=? AND owner_id=? AND process_type='RECYCLE' AND status='PENDING'",b.get("itemId"),b.get("applicantId"));return Map.of("message","回收申请已提交");}
 @GetMapping("/recycling-orders")public List<Map<String,Object>> recycling(@RequestParam long userId,@RequestParam(defaultValue="false")boolean admin){if(admin)admin(userId);String sql="SELECT ro.*,i.name item_name,s.name station_name FROM recycling_orders ro JOIN items i ON i.id=ro.item_id JOIN recycling_stations s ON s.id=ro.station_id"+(admin?"":" WHERE ro.applicant_id=?")+" ORDER BY ro.applied_at DESC";return db.queryForList(sql,admin?new Object[]{}:new Object[]{userId});}
 @PutMapping("/recycling-orders/{orderId}/status")public Map<String,Object> recycleStatus(@PathVariable long orderId,@RequestBody Map<String,Object>b){admin(id(b.get("operatorId")));String next=String.valueOf(b.get("status"));if(!Set.of("APPOINTED","PROCESSING","CANCELLED").contains(next))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"非法状态");db.update("UPDATE recycling_orders SET status=? WHERE id=?",next,orderId);return Map.of("message","状态已更新");}
 @PostMapping("/recycling-orders/{orderId}/complete")@Transactional public Map<String,Object> complete(@PathVariable long orderId,@RequestBody Map<String,Object>b){admin(id(b.get("operatorId")));Map<String,Object>o=db.queryForMap("SELECT ro.applicant_id,ro.item_id,i.category_id,c.point_factor FROM recycling_orders ro JOIN items i ON i.id=ro.item_id JOIN categories c ON c.id=i.category_id WHERE ro.id=? AND ro.status='PROCESSING'",orderId);double w=Double.parseDouble(String.valueOf(b.get("weightKg")));if(w<=0)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"重量必须大于0");int points=(int)Math.round(w*Double.parseDouble(String.valueOf(o.get("point_factor"))));db.update("UPDATE recycling_orders SET status='COMPLETED',completed_at=NOW() WHERE id=?",orderId);db.update("UPDATE items SET status='COMPLETED',completed_at=NOW() WHERE id=?",o.get("item_id"));db.update("INSERT INTO recycling_records(recycling_order_id,category_id,weight_kg,recycle_amount,contribution_points) VALUES(?,?,?,?,?)",orderId,o.get("category_id"),w,b.getOrDefault("recycleAmount",0),points);Long rid=db.queryForObject("SELECT id FROM recycling_records WHERE recycling_order_id=?",Long.class,orderId);db.update("INSERT INTO eco_point_records(user_id,recycling_record_id,change_points,reason) VALUES(?,?,?,?)",o.get("applicant_id"),rid,points,"完成物品回收");db.update("UPDATE users SET total_points=total_points+? WHERE id=?",points,o.get("applicant_id"));return Map.of("points",points,"message","回收完成，积分已入账");}
 @GetMapping("/points")public Map<String,Object> points(@RequestParam long userId){Map<String,Object>r=new HashMap<>();r.put("total",db.queryForObject("SELECT total_points FROM users WHERE id=?",Integer.class,userId));r.put("records",db.queryForList("SELECT * FROM eco_point_records WHERE user_id=? ORDER BY created_at DESC",userId));return r;}
 @GetMapping("/stats/overview")public Map<String,Object> stats(){Map<String,Object>r=new HashMap<>();r.put("monthly",db.queryForList("SELECT * FROM v_monthly_item_stats ORDER BY month"));r.put("categories",db.queryForList("SELECT * FROM v_category_stats"));r.put("methods",db.queryForList("SELECT process_type,COUNT(*) quantity FROM items GROUP BY process_type"));r.put("stations",db.queryForList("SELECT * FROM v_station_recycle_stats ORDER BY total_weight DESC"));r.put("ranking",db.queryForList("SELECT u.real_name,SUM(e.change_points) total_points FROM users u JOIN eco_point_records e ON e.user_id=u.id GROUP BY u.id,u.real_name ORDER BY total_points DESC"));return r;}
 @GetMapping("/admin/users")public List<Map<String,Object>> users(@RequestParam long operatorId){admin(operatorId);return db.queryForList("SELECT id,username,real_name,phone,role,status,total_points,created_at FROM users ORDER BY id");}
 @GetMapping("/admin/recycling-records")public List<Map<String,Object>> records(@RequestParam long operatorId){admin(operatorId);return db.queryForList("SELECT rr.*,i.name item_name,s.name station_name,u.real_name applicant_name FROM recycling_records rr JOIN recycling_orders ro ON ro.id=rr.recycling_order_id JOIN items i ON i.id=ro.item_id JOIN recycling_stations s ON s.id=ro.station_id JOIN users u ON u.id=ro.applicant_id ORDER BY rr.recycled_at DESC");}
}
